### ISSUE TITLE
Site launch checklist

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-pm.io#2]
- [x] Final logo in .svg format. 
- [x] Final tagline from Jimmy, if diff than what we have.
- [x] Final pre-launch review
- [x] rename master branch to gh-pages
- [x] enable GitHub Pages on repo
- [x] merge #3 to do final site publish
